# Generated by Django 3.1.7 on 2021-04-01 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('decscription', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('duration', models.IntegerField(default=60)),
                ('max_participants', models.IntegerField(default=10)),
                ('date_hosted', models.DateTimeField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('cover_photo', models.FilePathField(path=None)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.category')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
