# Generated by Django 3.1.7 on 2021-04-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='decscription',
            new_name='description',
        ),
    ]
