# Generated by Django 3.1.7 on 2021-04-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210407_1231'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('event', 'recipe')},
        ),
    ]
